/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.MainOfShowingContents;

import base.main;
import controllers.CourseController;
import controllers.PostController;
import entities.Course;
import entities.Post;
import entities.User;

/**
 *
 * @author zhaoxiling
 */
public class CommentsForm extends javax.swing.JFrame {
    private final User user;
    private final Course course;

    private final Post post;
    private Comment viewComment = null;
    private final CourseController courseController = main.courseController;
    private final PostController postController = main.postController;

    /**
     * Creates new form CommentsForm
     */
    public CommentsForm(User user, Course course, Post post) {
        this.user = user;
        this.course = course;
        this.post = post;
        initComponents();
    }

//    public CommentsForm(User user, Course course, Post post, Comment comment){
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        showingPostTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        gobackButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        showingUserLabel16 = new javax.swing.JLabel();
        showContentLabel16 = new javax.swing.JLabel();
        commentButton11 = new javax.swing.JButton();
        reportButton11 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Comment on:");

        showingPostTitleLabel.setText(post.getTopic());

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("List of All Comments"));
        jList2.setModel(new javax.swing.AbstractListModel() {
           final int commentsSize  = postController.getAllCommentFromPost(course.getCode(), post.getTopic()).size();
           String[] strings = getCommentArray(commentsSize);

//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }

        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        jList2MouseClicked(evt);
                                    }
                                });
        jScrollPane1.setViewportView(jList2);

        gobackButton.setText("Back to Post");

        jLabel3.setText("User:");

        UsernameLabel.setText(user.getUsername());

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Comments Description"));

        jLabel27.setText("Author:");

        showingUserLabel16.setText("Username");

        showContentLabel16.setText("jLabel4");

        commentButton11.setText("Comment on this comment");
        commentButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentButton11commentButtonActionPerformed(evt);
            }
        });

        reportButton11.setText("Report this comment");
        reportButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButton11reportButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Content:");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel18Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(commentButton11)
                                                .addGap(58, 58, 58)
                                                .addComponent(reportButton11))
                                        .addGroup(jPanel18Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel27)
                                                        .addComponent(jLabel28))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(showContentLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(showingUserLabel16))))
                                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(showingUserLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel28)
                                        .addComponent(showContentLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(commentButton11)
                                        .addComponent(reportButton11))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(gobackButton))
                                                .addContainerGap(29, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(showingPostTitleLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(UsernameLabel)
                                                .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(showingPostTitleLabel)
                                        .addComponent(jLabel3)
                                        .addComponent(UsernameLabel))
                                .addGap(9, 9, 9)
                                .addComponent(gobackButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void commentButton11commentButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void reportButton11reportButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int chosenCommentIndex = jList2.getSelectedIndex();
        Comment selectComment = post.getComments().get(chosenCommentIndex);
        viewComment = selectComment;
        changePanel(selectComment);

    }

    private void changePanel(Comment comment){
       showingUserLabel6.setText(comment.getPostedBy().getUsername());
       showContentLabel6.setText(comment.getTexts());

    }

    private String[] getCommentArray(int commentSize){
        String[] comments = new String[commentSize];
        for(int i = 0; i < commentSize; i ++){
            comments[i] = "Comment " + String.valueOf(i);
        }
        return comments;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CommentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CommentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CommentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CommentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CommentsForm(user, course, posts).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton commentButton;
    private javax.swing.JButton commentButton1;
    private javax.swing.JButton commentButton11;
    private javax.swing.JButton commentButton2;
    private javax.swing.JButton commentButton3;
    private javax.swing.JButton commentButton4;
    private javax.swing.JButton commentButton5;
    private javax.swing.JButton commentButton6;
    private javax.swing.JButton commentButton7;
    private javax.swing.JButton commentButton8;
    private javax.swing.JButton commentButton9;
    private javax.swing.JButton gobackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton reportButton1;
    private javax.swing.JButton reportButton11;
    private javax.swing.JButton reportButton2;
    private javax.swing.JButton reportButton3;
    private javax.swing.JButton reportButton4;
    private javax.swing.JButton reportButton5;
    private javax.swing.JButton reportButton6;
    private javax.swing.JButton reportButton7;
    private javax.swing.JButton reportButton8;
    private javax.swing.JButton reportButton9;
    private javax.swing.JLabel showContentLabel10;
    private javax.swing.JLabel showContentLabel11;
    private javax.swing.JLabel showContentLabel12;
    private javax.swing.JLabel showContentLabel13;
    private javax.swing.JLabel showContentLabel14;
    private javax.swing.JLabel showContentLabel16;
    private javax.swing.JLabel showContentLabel5;
    private javax.swing.JLabel showContentLabel6;
    private javax.swing.JLabel showContentLabel7;
    private javax.swing.JLabel showContentLabel8;
    private javax.swing.JLabel showContentLabel9;
    private javax.swing.JLabel showingPostTitleLabel;
    private javax.swing.JLabel showingUserLabel10;
    private javax.swing.JLabel showingUserLabel11;
    private javax.swing.JLabel showingUserLabel12;
    private javax.swing.JLabel showingUserLabel13;
    private javax.swing.JLabel showingUserLabel14;
    private javax.swing.JLabel showingUserLabel16;
    private javax.swing.JLabel showingUserLabel5;
    private javax.swing.JLabel showingUserLabel6;
    private javax.swing.JLabel showingUserLabel7;
    private javax.swing.JLabel showingUserLabel8;
    private javax.swing.JLabel showingUserLabel9;
    // End of variables declaration
}



