package UI.MainOfShowingContents;

import Presenter.GeneralPresenter;
import UI.PostingStuff.MakeACourse;
import UI.PostingStuff.MakeAReport;
import UI.UserdataRelated.ProfilePage;
import base.main;
import controllers.CourseController;
import entities.Course;
import entities.User;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author zhaoxiling
 */
public class CoursesForm extends javax.swing.JFrame {
    private final User user;
    private final ArrayList<Course> courses ;
    private final CourseController courseController = main.courseController;


    private Course viewCourse;
    /**
     * Creates new form CoursesForm
     */
    public CoursesForm(User user, ArrayList<Course> courses) {
        this.user = user;
        this.courses = courses;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        JLabel courseNameLabel = new JLabel();
        JButton registerButton = new JButton();
        jList2 = new javax.swing.JList();
        JPanel jPanel7 = new JPanel();
        JLabel jLabel8 = new JLabel();
        nameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        JButton showPostsButton = new JButton();
        JButton reportButton = new JButton();
        JLabel jLabel9 = new JLabel();
        codeLabel = new javax.swing.JLabel();
        JLabel jLabel11 = new JLabel();
        semesterLabel = new javax.swing.JLabel();
        JLabel jLabel13 = new JLabel();
        instructorLabel = new javax.swing.JLabel();
        JLabel jLabel15 = new JLabel();
        postsLabel = new javax.swing.JLabel();
        JLabel jLabel17 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel userLabel = new JLabel();
        JButton profileButton = new JButton();
        JLabel jLabel4 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseNameLabel.setText("Q&A Forum");

        registerButton.setText("Register A new Course");
        registerButton.addActionListener(this::registerButtonActionPerformed);

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("List of All Course"));
        jList2.setModel(new javax.swing.AbstractListModel() {
            final String[] strings = courseController.getAllCoursesName().toArray(new String[0]);


            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked();
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Description"));

        jLabel8.setText("Course Name:");

        nameLabel.setText("Name of the Course");

        descriptionLabel.setText("Description of the Course");

        showPostsButton.setText("show all posts under this course");
        showPostsButton.addActionListener(this::showPostsButtonActionPerformed);

        reportButton.setText("Report this course");
        reportButton.addActionListener(this::reportButtonActionPerformed);

        jLabel9.setText("Course Code");

        codeLabel.setText("Code of the Course");

        jLabel11.setText("Semester:");

        semesterLabel.setText("Semester");

        jLabel13.setText("Course Instructor:");

        instructorLabel.setText("Course Instructor");

        jLabel15.setText("Total Posts:");

        postsLabel.setText("Number of Posts");

        jLabel2.setText("Description of Course:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(showPostsButton)
                                                .addGap(55, 55, 55)
                                                .addComponent(reportButton))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nameLabel)
                                                        .addComponent(codeLabel)
                                                        .addComponent(semesterLabel)
                                                        .addComponent(instructorLabel)
                                                        .addComponent(postsLabel)
                                                        .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(codeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(semesterLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(instructorLabel)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(postsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(showPostsButton)
                                        .addComponent(reportButton))
                                .addContainerGap(66, Short.MAX_VALUE))
        );

        userLabel.setText(user.getUsername());

        profileButton.setText("Profile Page");
        profileButton.addActionListener(this::profileButtonActionPerformed);

        jLabel4.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(registerButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jList2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 72, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(courseNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(userLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(profileButton)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseNameLabel)
                                        .addComponent(userLabel)
                                        .addComponent(profileButton)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jList2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (this.viewCourse == null){
            GeneralPresenter.showNotSelectError("Course");
        } else {
            MakeAReport makeAReport = new MakeAReport(this.user, this.viewCourse);
            makeAReport.setVisible(true);
            this.setVisible(false);
        }
    }

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        MakeACourse makeACourse = new MakeACourse(this.user);
        makeACourse.setVisible(true);
        this.setVisible(false);

    }


    private void jList2MouseClicked() {
        int chosenCourseIndex = jList2.getSelectedIndex();
        if(chosenCourseIndex==-1){
            GeneralPresenter.showNotSelectError("Course");
        }
        else {
            Course selectCourse = courses.get(chosenCourseIndex);
            changePanel(selectCourse);
            this.viewCourse = selectCourse;
        }
    }

    private void changePanel(Course course){
        nameLabel.setText(course.getName());
        codeLabel.setText(course.getCode());
        semesterLabel.setText(course.getSemester());
        instructorLabel.setText(String.valueOf(course.getInstructor()));
        postsLabel.setText(String.valueOf(course.getPosts().size()));
        descriptionLabel.setText("<html>"+course.getDescription()+ "</html>");
    }

    private void showPostsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.viewCourse == null){
            GeneralPresenter.showNotSelectError("Course");
        } else {
        PostForm postForm = new PostForm(user, viewCourse);
        postForm.setVisible(true);
        this.setVisible(false);
        }
    }
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ProfilePage profilePage = new ProfilePage(this.user, this.user, this.viewCourse);
        profilePage.setVisible(true);
        this.setVisible(false);
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JList jList2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel postsLabel;
    private javax.swing.JLabel semesterLabel;
    // End of variables declaration
}
